SBI_BANK:INVOKE_FIRST.connection.Connection URL=${{REST_URL}}
SBI_BANK:INVOKE_FIRST.connection.Connection Type=restUrl
SBI_BANK:SOAP_TEST.secure.Username=manager
SBI_BANK:SOAP_TEST.secure.Password=${{SBI_MNGR_PWD}}
