SBI_BANK:INVOKE_FIRST.connection.Connection URL=${{REST_URL}}
SBI_BANK:INVOKE_FIRST.connection.Connection Type=restUrl
SBI_BANK:SOAP_CONN.secure.Username=manager
SBI_BANK:SOAP_CONN.secure.Password=${{SBI_MNGR_PWD}}
RAJ:INVOKE_FIRST.connection.Connection URL=${{REST_URL}}
RAJ:INVOKE_FIRST.connection.Connection Type=restUrl
RAJ:SOAP_CONN.secure.Username=manager
RAJ:SOAP_CONN.secure.Password=${{SBI_MNGR_PWD}}
RAJ_FTP2.secure.Password=password
